# Generated by Django 3.2.7 on 2021-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_Name', models.CharField(max_length=200)),
                ('Donor_Name', models.CharField(max_length=200)),
                ('Donor_Phone', models.CharField(max_length=10)),
            ],
        ),
    ]
