# Generated by Django 3.2.7 on 2021-10-19 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(max_length=350)),
                ('BloodType', models.CharField(choices=[('A+', 'a+'), ('B+', 'b+'), ('O+', 'o+'), ('AB+', 'ab+'), ('A-', 'a-'), ('B-', 'b-'), ('O-', 'o-'), ('AB-', 'ab-')], default='A+', max_length=9)),
                ('Age', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(18)])),
            ],
        ),
    ]
