# Generated by Django 3.2.7 on 2021-10-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donors',
            new_name='donor',
        ),
    ]
