# Generated by Django 3.2.7 on 2021-10-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0002_rename_donors_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='BloodType',
            field=models.CharField(choices=[('a+', 'A+'), ('b+', 'B+'), ('o+', 'O+'), ('ab+', 'AB+'), ('a-', 'A-'), ('b-', 'B-'), ('o-', 'O-'), ('ab-', 'AB-')], default='A+', max_length=9),
        ),
    ]
