# Generated by Django 3.2.7 on 2021-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0003_alter_donor_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='BloodType',
            field=models.CharField(choices=[('a+', 'A+'), ('b+', 'B+'), ('o+', 'O+'), ('ab+', 'AB+'), ('a-', 'A-'), ('b-', 'B-'), ('o-', 'O-'), ('ab-', 'AB-')], max_length=9),
        ),
    ]
