# Generated by Django 3.2.7 on 2021-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0005_rename_age_donor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(verbose_name=False),
        ),
    ]
