# Generated by Django 3.2.7 on 2021-10-19 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0007_alter_donor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator]),
        ),
    ]
