# Generated by Django 3.2.7 on 2021-10-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0011_alter_donor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='medical_ailments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
