# Generated by Django 3.2.7 on 2021-10-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0013_alter_donor_medical_ailments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='medical_ailments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
