# Generated by Django 3.2.7 on 2021-10-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donateBlood', '0014_alter_donor_medical_ailments'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
